### ISSUE TITLE
Update feature does not open a terminal and execute the update command "yay --noconfirm"

### ISSUE THREAD

**Issue by Mshmaitelly** [dhruv8sh/arch-update-checker#1]
When I hit the "download arrow" meaning execute "install the new packages" using the command "yay --noconfirm" there is no terminal/console launched where the command should be executed.

The KD5 version had this option, plus a user choice of auto-closing the terminal after the installation is complete.

**Comment by Mshmaitelly** [comment]
I will check and verify. Both Konsole and yay are installed.

**Comment by Mshmaitelly** [comment]
I may have mistyped the execution command: "yay --noconfirm" as yay --nocomfirm",
Re-testing and I am sorry if it was a false alarm on my end.

**Comment by dhruv8sh** [comment]
It's no problem, although thanks to that, I have spotted a couple other bugs as well.

**Comment by Mshmaitelly** [comment]
[Rejected] mistyped execution command. The execution command should be: yay --noconfirm
