### ISSUE TITLE
Console is closing though it's set to not

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [dhruv8sh/arch-update-checker#10]
Regardless of the setting "Do not close konsole" the konsole window is closing after a full system update, as well as after the installation of an individual package.

**Comment by dhruv8sh** [comment]
I am aware of the really buggy experience but due to my really busy schedule I am only able to give 30 mins per week to each of my projects.
I will try my best to get it to work in the next 24 hrs alongside the notification feature. Meanwhile please report any other issues you have with this.

**Comment by JackLeEmmerdeur** [comment]
Hey!
Github issues shouldn't be a liability especially if it's your own project and you got a busy schedule.
You already gifted a great applet to the community. I'm using it daily. Thanks for your work.
I don't see the buggy experience at all. The console not closing is literally the only bug left I spotted and it's non-critical.
Have fun and don't let this be a chore.

**Comment by dhruv8sh** [comment]
Fixed in the latest commit!
Thank you for using this applet.

**Comment by QuarkZ26** [comment]
This still seems to still be an issue, the console closes after I run the udpate.

**Comment by dhruv8sh** [comment]
Did you install the last release or the last commit?
