### ISSUE TITLE
Menu not expanding

### ISSUE THREAD

**Issue by migueacastro** [dhruv8sh/arch-update-checker#12]
Recently installed it with the commands provided. It's added to the panel but it's not expanding when clicked

![image](https://github.com/dhruv8sh/arch-update-checker/assets/54249734/0347a79f-b242-488d-8cab-e726a741a961)

**Comment by dhruv8sh** [comment]
Closing for being a duplicate of #11.

**Comment by dhruv8sh** [comment]
Should be fixed in the latest commit. See #11 for more details.
