### ISSUE TITLE
bug: can't type custom poll intervals

### ISSUE THREAD

**Issue by Haraven** [dhruv8sh/arch-update-checker#13]
### Description

The widget works wonderfully, with one exception: configuring the poll interval for updates is buggy. I want to configure the widget so that it only checks for updates once per day (every 1440 minutes). Currently, I can't do that.

### Steps to Reproduce

1. install the widget
2. open widget configuration menu
3. select the poll interval field and type a new value, e.g., 1440
4. notice how the apply button isn't active even if you click outside the input field

AND

1. install the widget
2. open widget configuration menu
3. press the up arrow button in the poll interval field
4. keep pressed until it reaches a high value, e.g., 300 minutes
5. press apply
6. watch as the value resets to 1 (sometimes this works, and sometimes it doesn't)

### Expected Behavior

You should be able to 1) type poll interval values and apply them, and 2) set the poll interval to a high value, like 300 minutes or more.

### Actual Behavior

Currently, I have to use the up/down buttons to change poll interval - I can't type a custom value. Also, often, when I try to set the poll interval to a high value, like 300 minutes, applying resets back to 1.

### Environment

- Linux Distro: base Arch
- Linux Version: 6.8.1-zen1
- Plasma version: 6.0.2

**Comment by dhruv8sh** [comment]
Should not happen at all, it's not editable in that it. You were not on the latest version.
Anyways, I tweaked it look better:
![image](https://github.com/dhruv8sh/arch-update-checker/assets/67322047/26095d90-5094-43f3-9c2d-7705350d92a1)

Make sure to put in any other suggestions you have.
The next release will include this along with major refactors to the configuration pages.

**Comment by dhruv8sh** [comment]
The new release was just pushed to the store.
Enjoy and keep using Plasma.

**Comment by Haraven** [comment]
I was indeed using an older version. For some reason I don't have the option to update the widget from the store. I had to uninstall and reinstall it. 

Works fine now!

Thanks very much.
