### ISSUE TITLE
[Feature Request] - Alacritty support

### ISSUE THREAD

**Issue by itouchdennis** [dhruv8sh/arch-update-checker#16]
I do not use konsole as my terminal and don't have it installed as I use just the "small" installation, not the full one of plasma kde alacritty.

When I click update system in the panel I get the "konsole" command not found issue.

Not a big deal - I just workarounded it with linking bin/konsole to bin/alacritty, but it would be nice if the user can configure / freetext input the personal used terminal update command

**Comment by dhruv8sh** [comment]
It is planned(look at the readme). I'll move it up the priority list if this is really needed.

**Comment by itouchdennis** [comment]
Havent recognized it in the roadmap - ty!

Another short hint: in your "about" section is a github link to this project containing a small typo leading into:

https://github.com/dhurv8sh/arch-update-checker

instead the correct github url (at least on 0.7.11 might be differ in the newer version)

**Comment by dhruv8sh** [comment]
Yea, I'll fix this in the next release. Thanks for pointing it out!

**Comment by dhruv8sh** [comment]
This was fixed in the latest merge.
