### ISSUE TITLE
Change installation process in readme

### ISSUE THREAD

**Issue by Deinorius** [dhruv8sh/arch-update-checker#17]
First, thank you for this plasmoid. I already mentioned a few suggestions on reddit but I saw that your installation explanation uses `plasmapkg2` which is outdated in Plasma 6 AFAIK.
The new pkg used for this is named `kpackagetool6` with the same arguments.

Another question because I already suggested this on reddit. Can you add pamac as AUR wrapper?

**Comment by dhruv8sh** [comment]
Cool. Pamac will be added in the next release.

**Comment by Deinorius** [comment]
Great. Appreciate it.

**Comment by dhruv8sh** [comment]
I have been working on a new feature that will benefit this and hopefully other projects.
Expect a release tomorrow with a bunch of features.

**Comment by Deinorius** [comment]
Even other projects? Interesting, already curious.

**Comment by dhruv8sh** [comment]
The readme change was made, thanks!
Didn't use pamac before this so didn't know it is a standalone package manager instead of a Wrapper around AUR. This is easy to add but I'll add it later, only if it is needed.
It calls pacman internally anyways, so I don't currently see the relevance of this.

**Comment by dhruv8sh** [comment]
Yes, true!
Since, other people are asking for it, guess we're adding pamac. See #23.
Can you please open another issue for choosing no AUR Wrapper at all?

**Comment by dhruv8sh** [comment]
Pamac support was added in the latest release
