### ISSUE TITLE
[Request] Show which repo a package is from

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#18]
Show whether a package is from core/extra etc would be nice, maybe even use color coding for it.
Cool widget, thanx for making it!

**Comment by dhruv8sh** [comment]
Cool.

**Comment by dhruv8sh** [comment]
I have fixed this and in my opinion it should work. I don't currently have any packages to test this on, maybe you can install the latest commit and try ?
I will close the issue for now, but we can reopen if it does not work.

**Comment by Kingproone** [comment]
Where would this option be displayed? because I can't seem to find it.

(kpackagetool6 -i . failed in (installing/)registering the applet into the installed widgets list even though it said installed successfully, plasmapkg2 -i . worked fine though)

**Comment by dhruv8sh** [comment]
It is non-toggleable and should work out of the box.

**Comment by Kingproone** [comment]
ok, I see it before the version numbers, looks nice, thank you

**Comment by dhruv8sh** [comment]
Perfect!

**Comment by Kingproone** [comment]
It misreports extra package as an aur one (plus I'm not sure how endeavour indexes their packages, so aur might be correct in that case)
![Screenshot_20240420_143745](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/bfbc1093-1b36-4bf1-8261-00ea3aacfbcc)

**Comment by dhruv8sh** [comment]
Okay, I will fix this tomorrow.

**Comment by dhruv8sh** [comment]
Fixed!

**Comment by Kingproone** [comment]
Beautiful!
