### ISSUE TITLE
[BUG] After an update the screen falshes black

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#19]
So I use plasma 6, with yay as pacman wrapper and Konsole as terminal (endeavouros), and when it gets to the end, the whole screen turns black for like ~1 second (this happenned for 2 times already) then it comes back, but my panel gets killed too, which has to restart as well, it's as if at the end of the update it restarts my whole shell or at the very least crashes it for some reason.
I don't know what logs I could provide.

**Comment by Kingproone** [comment]
i will check again tomorrow with an update to see if the issue persists,
yay -Syu runs just fine on the daily, as for the logs:

$ plasmashell --replace
KPackageStructure of KPluginMetaData(pluginId:"split-clock", fileName: "/home/endeavour/.local/share/plasma/plasmoids/split-clock/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.plasma.kweather_1x4", fileName: "/usr/share/plasma/plasmoids/org.kde.plasma.kweather_1x4/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.plasma.kclock_1x2", fileName: "/usr/share/plasma/plasmoids/org.kde.plasma.kclock_1x2/metadata.json") does not match requested format "Plasma/Applet"
kf.coreaddons: The plugin "/usr/lib/qt6/plugins/plasma/applets/plasma_applet_kweather_1x4.so" explicitly states an Id in the embedded metadata, which is different from the one derived from the filename The Id field from the KPlugin object in the metadata should be removed
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
org.kde.plasma.kicker: Entry is not valid "applications:org.kde.krita.desktop" 0x0
org.kde.plasma.kicker: Entry is not valid "applications:org.kde.kwikdisk.desktop" 0x0
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:162:21: QML KSortFilterProxyModel: Binding loop detected for property "sourceModel"
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:162:21: QML KSortFilterProxyModel: Binding loop detected for property "sourceModel"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/ThumbnailStrip.qml"
qml: SystemTray ItemLoader: Invalid state, cannot determine source!
qt.dbus.integration: Could not connect "org.cups.cupsd.Notifier" to PrinterFinishingsChanged(QString, QString, QString, uint, QString, bool) : 
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0

**Comment by dhruv8sh** [comment]
I am sorry, completely forgot to mention.
Run ```plasmashell --replace``` and then perform and update through the applet.

**Comment by Kingproone** [comment]
So i tested it again after running plasmashell --replace, and 0.7.11 both installed from the command line and from the get new things dialog menu worked fine, and 0.8.5 works fine too, so I think this can be closed.

**Comment by dhruv8sh** [comment]
It must've been an issue with a singular package upgrade.
