### ISSUE TITLE
[Request] Support other pacman alternatives?

### ISSUE THREAD

**Issue by Ronco23** [dhruv8sh/arch-update-checker#23]
Planned to support other cli wrappers or package managers/helpers like Manjaro's pamac?

**Comment by dhruv8sh** [comment]
You see, pamac is not an AUR Wrapper. Rather it's a standalone package manager like pacman.
Adding it makes less sense the more you think about it.
It calls pacman internally anyways, but since more people have been asking for it, I guess we're adding it.

**Comment by Ronco23** [comment]
I understand that, maybe we'll need a Manjaro version of this applet, rather than including pamac into this one

**Comment by dhruv8sh** [comment]
I'll add a toggle for it rather!

**Comment by dhruv8sh** [comment]
pamac support added in the latest commit.
