### ISSUE TITLE
Update checker notification too anoying and can't be disabled

### ISSUE THREAD

**Issue by OlegAckbar** [dhruv8sh/arch-update-checker#27]
I have this useless notification which shows every 15 minutes informing me that there are no updates. Can you add an option to disable it entirely, pls?
![изображение](https://github.com/dhruv8sh/arch-update-checker/assets/9915567/fa4263b7-e059-46ce-acc8-287b61e2c6f6)

**Comment by dhruv8sh** [comment]
The latest update fixes the problem of notifying over zero updates.
I will add a toggle for it in the next release.

**Comment by dhruv8sh** [comment]
Fixed! My bad.
I would wait about 10 minutes before the update shows up on the store.
