### ISSUE TITLE
[Request] toggle to switch off notifications

### ISSUE THREAD

**Issue by kinoegit** [dhruv8sh/arch-update-checker#28]
The newly implemented feature of system notification prompts when a an update check was made. Notifications are shown in any case of pending updates or no updates. 
Would you mind to supply an option to disable notifications via preferences of the app. 
Disable notification separately per app via system notifications settings would be another way. But I didn't find arch update checker among the list of apps to disable notifications. 

Distribution: Arch Linux, Desktop: KDE Plasma6, arch update checker version: 0.8.3

**Comment by dhruv8sh** [comment]
Fixed! My bad. Wait a few minutes and update should show on the store.

**Comment by kinoegit** [comment]
Thank you! Fast as lightning!
