### ISSUE TITLE
[Bug] Checkupdates: command not found

### ISSUE THREAD

**Issue by Bookingyo** [dhruv8sh/arch-update-checker#29]
Getting this error when I open the tab. Am I missing a dependency?

```
Command:checkupdates
Error code: 127
/bin/sh: line 1: checkupdates: command not found
```

![image](https://github.com/dhruv8sh/arch-update-checker/assets/66762796/d0cb6a80-ed7c-4e95-9f8d-84dc328bee0a)

**Comment by dhruv8sh** [comment]
You need to install pacman-contrib package. Seems like you have a really minimal install.
