### ISSUE TITLE
Doesn't display correctly with panel colorizer

### ISSUE THREAD

**Issue by Kevadroz** [dhruv8sh/arch-update-checker#3]
![Captura de pantalla_20240316_173548](https://github.com/dhruv8sh/arch-update-checker/assets/16049149/bdaaf3df-56d2-44b4-a97b-65499f9baefa)
The update counter text is not visible, presumably tinted in the same color as the background circle.

**Comment by dhruv8sh** [comment]
This is a problem with the colorizer applet. It colors everything the same color resulting in this behavior, hence affecting all applets which have text on a background.
There is no fix that can be applied on this end to solve this.
<br/>

**Workarounds**:
- Apply an exception in the colorizer applet for "org.kde.archupdatechecker"
- Use custom colors from the config page.
<br/>

**Extra info if you need it:** The colorizer engine sets the Kirigami.Theme.backgroundColor and Kirigami.Theme.textColor to the same value.

**Comment by Kevadroz** [comment]
> There is no fix that can be applied on this end to solve this.

Using `org.kde.plasma.workspace.components BadgeOverlay` for the badge would solve this, but that would also an aesthetic change.

**Comment by dhruv8sh** [comment]
I would argue that would solve the problem either. Look at the native battery applet.
![image](https://github.com/dhruv8sh/arch-update-checker/assets/67322047/bbf90441-88ce-4236-baa7-2ac82317e097)
There is near zero contrast on darker colors.
