### ISSUE TITLE
[Bug] after pressing the `Update your system` button, its tooltip remains visible 

### ISSUE THREAD

**Issue by Haraven** [dhruv8sh/arch-update-checker#31]
## Description

If you move your mouse over the  "Update your system" button, wait for the tooltip to appear, and then you press the button, the tooltip gets stuck on-screen. It only goes away if you click on the panel, somewhere near the tooltip.

## Demo

https://github.com/dhruv8sh/arch-update-checker/assets/10146027/3027ec02-2496-47e3-af18-b08109844a75

## Steps to reproduce

1. Open the Arch Update Checker widget
2. Hover over the update button
3. Wait for the button tooltip to appear
4. Press the update button

## OS information

- Plasma version: 6.0.3
- Plasmoid version: 0.8.5 (latest available from KDE store)

**Comment by Kingproone** [comment]
This has happened to me too, but wasn't as noticeable since I use a vertical panel.

**Comment by dhruv8sh** [comment]
Wierd. Plasma should handle this internally.
I'll add a line to make it explicitly disappear when clicked. The next release is in about 6 hours, will be fixed in that.

**Comment by dhruv8sh** [comment]
Fixed.

**Comment by Haraven** [comment]
Awesome, thank you!
