### ISSUE TITLE
Issues Scaling Badge

### ISSUE THREAD

**Issue by cryofault** [dhruv8sh/arch-update-checker#32]
The update badge scales unevenly whenever the panel height is increased. The screenshot shows the panel set to a height of 58 with panel icon size set to the default small setting.

![image](https://github.com/dhruv8sh/arch-update-checker/assets/25939455/1b7b0e44-8ae1-46d7-a594-b93eadf820d5)

**Comment by dhruv8sh** [comment]
I did not think of this edge case, I will fix it today.

**Comment by dhruv8sh** [comment]
Should work better now after the latest commit.
