### ISSUE TITLE
Adding the option to select no AUR helper at all

### ISSUE THREAD

**Issue by Deinorius** [dhruv8sh/arch-update-checker#33]
As I mentioned it in another thread. Different people might just prefer to only use pacman. Either because they use no AUR (but Flatpak instead) or they have additional repos like chaotic-aur.

**Comment by dhruv8sh** [comment]
This was already added. Please install the latest version!

**Comment by Deinorius** [comment]
Ah, I was confused at first because the version on store.kde.org is not the latest, so I didn't get the newest features.

Then I installed it directly from this page but I had to manually copy the files to XDG_DATA_HOME/plasma/plasmoids/org.kde.archupdatechecker because kpackagetool6 installed it to XDG_DATA_HOME/kpackage/generic/org.kde/archupdatechecker instead. In that folder it wasn't available.

**Comment by Deinorius** [comment]
I personally don't need this, rather for you to know if someone has a similar problem.
IMO plasma-framework5 (for Arch) is no option because I got rid of all qt5 packages with my migration to Plasma 6 and I just tried it, had to install 47 packages with 240 MiB install size. That's not worth it in my book.
