### ISSUE TITLE
Nuvola is discontinued

### ISSUE THREAD

**Issue by tdtooke** [dhruv8sh/arch-update-checker#34]
This is not really an issue but the only annoyance you have with this are from the error because it can't connect to tiliado.eu for flatpak stuff.  I think you can safely remove all references to that.  Nuvola seems to be dead.  I just looked at their github page: https://github.com/tiliado/nuvolaplayer?tab=readme-ov-file

Edit:  For ex, this: https://web.archive.org/web/20201218005658/https://nuvola.tiliado.eu/  is what tiliado.eu used to be and
this: https://tiliado.eu/ is what it is now.  The thing querying that site will never work again.

**Comment by dhruv8sh** [comment]
The applet does not make any explicit reference to the Nuvola Player. Not sure what you are talking about here. Please elaborate.

**Comment by tdtooke** [comment]
I'll post a pic: [url]https://postimg.cc/YjdqWPSW[/url].  You can see this is the error message we've talked about before.  If you read it, it says "error: unable to load summary from remote Nuvola: While fetching https://dl.tiliado.eu/flatpak/nuvola/"  What I'm saying is that error is never going to go away because nuvola as a flatpak entity doesn't exist anymore.  I have no idea how your applet works.  Maybe it's querying a flatpak hub that has references in it to various flatpak sites.  If that's the case then nuvola needs to be removed as a provider there.  But somewhere there is something that is causing it to query a now non existent flatpak server.

**Comment by dhruv8sh** [comment]
Can you paste the output of ```flatpak remote-ls --app --updates```?

**Comment by tdtooke** [comment]
I'm one step ahead.  You're right.  It was from me still having nuvola as one of my providers.  I used to use it a lot.  I did flatpak remote-delete nuvola and it went away.  Sorry about that.  Never had to learn enough about flatpak to do something like that before.

**Comment by dhruv8sh** [comment]
Assuming the issue is safe to close then.
