### ISSUE TITLE
[Bug] Stutters when scrolling through large list

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#35]
I haven't used my system for a little and it has 200+ updates available at the moment, when scrolling through them the widget stutters (but does not freeze), v 0.8.5.

**Comment by dhruv8sh** [comment]
The applet uses native components to display these items and is as minimal as can be.
In fact, the details about a package is loaded after the click happens. Testing did not show any stuttering for me. Maybe you can record a video?

**Comment by Kingproone** [comment]
Well, since then I did an upgrade and I don't have that many packages, plus I updated to the latest kde stuff, which might change things, so I guess I can wait on updating a while.

**Comment by Kingproone** [comment]
This might be a relevant plasma bug, or at least similar in nature, i don't know if the applet uses the same things under the hood, and whether it gets overloaded too. I will be sure to upload a video as soon as there are more updates available for me.
https://bugs.kde.org/show_bug.cgi?id=483205

**Comment by dhruv8sh** [comment]
Hmm... I see! I can add a flag under the debug configuration group to disable highlights.

**Comment by Kingproone** [comment]
What would that turn off?

**Comment by dhruv8sh** [comment]
The highlight when you hover over a list item. This is the only operation I can think of that would affect performance like that.

**Comment by dhruv8sh** [comment]
https://imgur.com/a/5gSFqyP
There is no stutters for me when there are 218 packages to update. This issue might be on your personal system.
This issue will now be closed. Ask to reopen if this issue is consistent.

**Comment by Kingproone** [comment]
So this wasn't happening to me when scrolling with the wheel, rather when grabbing the scroll bar and dragging it (though I could see it happen if using a mouse which has a wheel that can spin freely, therefore going so fast as dragging the bar). Above a certain speed it starts stuttering. Clicking into the scrollbar, pretty much anywhere only takes at most ~half a second to load even at 500 updates available.

**Comment by Kingproone** [comment]
I found, that in plasmas emoji picker app, a similar behaviour appears, when dragging fast, or even clicking far away, it needs tim to load in, so this might be a plasma performance issue in the end.

**Comment by dhruv8sh** [comment]
Weirdly this does not happen for me in either case. Try running Plasma on your discrete graphics card. See if the issue persists.
