### ISSUE TITLE
[Bug] Number of updates touching the background/ the circle/pill not being big enough to cover it

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#36]
I don't know if this happens after 100, or with another font 

![Screenshot_20240415_105814](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/6e2f88fb-94ed-4034-83cb-691ef60c2b3c)

**Comment by Kingproone** [comment]
vertical spacing in the pill is off a bit as well, there is more whitesapace under the number than above

**Comment by dhruv8sh** [comment]
Fixed!
