### ISSUE TITLE
[Feature] Custom number of packages triggers the "shown when relevant" option

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#37]
I don't know how feasible/popular this would be, but the idea is simple. You can set system tray entries to be shown when they are relevant and you could change how many packages would hit that bar for you eg. 10 or 33. This way your panel could be cleaned up a little while not having to hide the applet, because there is always an update on arch (from which the project already discourages users to update only one package).

**Comment by dhruv8sh** [comment]
Yes this should be easy to implement. I am currently busy with some other applets, I'll get back to this in a couple days.

**Comment by dhruv8sh** [comment]
Fixed!
