### ISSUE TITLE
[Bug] Misaligned text in the extended info sections

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#38]
v 0.8.5
When not having enough items to have a scrollbar appear by default and expanding the infobox of a listed item, the appering scrollbar displaces the shown lines cutting them off. It seems to mostly affect the bottom most item in the list, but in the second recording when opening the first item it seems to jump a litlle as well.
[Screencast_20240420_134445.webm](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/68608adf-24e4-4f89-a745-3c48706b833f)
[Screencast_20240420_134719.webm](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/993a3425-1095-4d8e-aa93-5fa0e7ac5d1b)

**Comment by Kingproone** [comment]
It happens with v 0.8.9 too :(

**Comment by Kingproone** [comment]
or not, weird, it happened once, but seems to have fixed itself

**Comment by Kingproone** [comment]
It did come back in 0.8.9 
[Screencast_20240422_135544.webm](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/b4dcb4b5-8066-47eb-97ae-e47de6bd2fb9)

**Comment by Kingproone** [comment]
On top of it happening in random places it can also have a different deviation
![Screenshot_20240423_1025081](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/572acf3d-9d9d-4617-a79c-7ad7296a54c4)

**Comment by dhruv8sh** [comment]
Already, fixed locally, will be shipped in the next release.

**Comment by dhruv8sh** [comment]
Latest commit shipped this fix alongside other improvements. I'll publish a release.
