### ISSUE TITLE
[Feature] List new dependencies that will be installed by an update

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#40]
There is a new package that will be pulled for me when updating, and even though it is listed in the command line, it might just be missed when `--noconfirm` is on by default and the lines race by.

I don't know about this one, since someone who has noconfirm on will want their system to update without a fuss, but then again, something new will be installed on your system so it might be worthwile to show that in the applet, maybe even as a first entry.

![Screenshot_20240421_105702](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/2ce80e93-5a7f-42a1-9806-a330fffc8034)

2nd picture to show that it is listed, so the argument could be made again, that it is not necceseary to show that in the applet

![Screenshot_20240421_110947](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/2d352101-4a3c-42f7-ab2f-ee9d6432845b)

**Comment by dhruv8sh** [comment]
This might not be possible within the context the applet is running in. This will be closed as not planned, this can be re-opened once we find a way to implement this.
