### ISSUE TITLE
[Bug] Press any key not working

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#44]
When the "do not close terminal after an update" option is checked, and the update finishes, it asks for any button input, but for me it only takes enter.

**Comment by dhruv8sh** [comment]
This was fixed in the release made yesterday. I see you a regular contributor in issues, you might notice a massive time improvement in fetching updates over previous version, with more consistency all throughout the widget.
Thank you so much for using the applet and frequently contributing.

**Comment by Kingproone** [comment]
Thank YOU so much for this great little applet! It is very handy to have.

**Comment by tdtooke** [comment]
Thought I'd tack on a comment here since I just want to say something and this isn't an issue.  This applet has officially become the best arch update tool I've ever used.  Thank you for this.

**Comment by dhruv8sh** [comment]
Thanks. This means alot.
