### ISSUE TITLE
[Feature] Change the arch update news icon when there is a new entry

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#46]
So I don't know how it is implemented, or if the list is cached at all, but my idea would be to check the news upon opening the widget (this could be in the background too, for less friction), and compare the list that has been cached (if u use cache), if there is no cache the latest entry could be saved for reference. The icon could get an exclamation mark.

**Comment by dhruv8sh** [comment]
Yea. This feature has been implemented, I'll push it when I get back home.

**Comment by Kingproone** [comment]
Sorry for reading your mind? :P

**Comment by dhruv8sh** [comment]
Lol

**Comment by dhruv8sh** [comment]
Unfortunately this feature could not make it. It is really inconsistent and expensive in my opinion.
I figured it can be delayed as it is not a crucial feature. I will add it to the README todo list.

**Comment by dhruv8sh** [comment]
This will not be implemented due to its inconsistent nature. We can only fetch the entire news at once. I do not want to pre-cache the entire news as it could be long sometimes, and thus heavy on RAM.
