### ISSUE TITLE
[Bug] 0.9.6 First time setup doesn't save options.

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#48]
When clean installing (from get new widget dialog) and going through the setup, it only saved the changes made on the last? screen: for what string you want to display between version numbers, the before pages didn't save the changes I made.

(This was on a laptop with a clean plasma 6 install, which does not include `plasmapkg2` tool, but for some reason `kpackagetool6` didn't work either)

**Comment by dhruv8sh** [comment]
kpackagetool6 is currently broken. You should install from the store for a simpler install.
The intro pages save the config for me. Can you enable intro pages from debug option and retest?

**Comment by Kingproone** [comment]
Maybe update the readme, to suggest the `get new` dialog for obtaining the applet as the first option? That seems to be the most reliable.

**Comment by Kingproone** [comment]
1. deleted the widgets folder from `/home/USER/.local/share/plasma/plasmoids/`
2. ran `systemctl --user restart plasma-plasmashell`
3. redownloaded `from get new widgets`
4. it did not show the first time startup

take 2
1. deleted it from within the get new widgets window
2. reinstall it from there
3. it was properly added to the system tray, here are the default values, to what I changed them to, and what it remembered:

![Screenshot_20240516_134328](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/0d84a42b-7bf4-480b-84fb-b4244c73eb4b)
![Screenshot_20240516_134332](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/7d5ac437-1cec-45e2-9e2a-76cea4a8584f)
note that its hard to read the options in dark mode as well:
![Screenshot_20240516_134340](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/9f8d5f50-a3b3-4a5f-98c2-e8d67384a444)
![Screenshot_20240516_134345](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/fc648c6e-e305-4369-88fe-a65a4b16427c)
![Screenshot_20240516_134409](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/a8a7afcf-7044-493e-b67a-a1c10cd2bb42)
![Screenshot_20240516_134422](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/4d593cc5-6845-4bc4-9021-cb3390e5c744)
![Screenshot_20240516_134428](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/16283e1f-560c-444d-b39b-87e35e1caf82)
![Screenshot_20240516_134432](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/ac3b70d7-f92e-472e-a9db-8e0a7aa69d36)
![Screenshot_20240516_134457](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/77a9ceaf-10dd-46ba-ac38-119d249f6639)
![Screenshot_20240516_134501](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/ba08e391-700d-4f83-9144-4cf522665904)
![Screenshot_20240516_134505](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/3238110c-e93e-4a0b-a9dc-dc674a6ffbaa)

**Comment by dhruv8sh** [comment]
- There is a rewrite under works for this, until it is complete I have disabled Intro pages by default.
- The dark text issue is not making any sense to me either. The text is dark only the first time when opening the drop down menu.
- The saving of the config values dynamically seems inconsistent and a fix will be applied.
- I'll add a minimum size for pages, so that the author is not cut-off.

**Comment by dhruv8sh** [comment]
This has been deprecated and will be removed in the next version.
