### ISSUE TITLE
Give more information about the installation in the readme, prefer "get new things" dialog

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#50]
Suggestion:

Use the `Download new widget` functionality to obtain the widget (currently there are no auto updates for widgets on plasma 6, and you can't update them via the update button, [relevant](https://bugs.kde.org/show_bug.cgi?id=483570) [issues](https://discuss.kde.org/t/kde-6-widgets-fail-to-update/14337))

If the applet doesn't get automatically added to your system tray, run:
`systemctl --user restart plasma-plasmashell` - this will restart your plasma shell
or log out and back in.

Alternatively you can use `kpackagetool6` (currently broken) or `plasmapkg2` (not part of a clean plasma 6 install)

```
git clone https://github.com/dhruv8sh/arch-update-checker/
cd arch-update-checker
kpackagetool6 -i .
```

**Comment by Kingproone** [comment]
I couldn't find the bug report about no auto updates, at least I thought it is open somewhere, but the only place I know it from, is niccolove mentioned it in a video. that could be added as well one way or another.

**Comment by Kingproone** [comment]
I have a few more formatting pointers:

#### Required:
You need to install `pacutils` and `pacman-contrib` packages for the applet to work correctly.

```
sudo pacman -S pacutils pacman-contrib.
```
#### Recommended method:
Use the `Download new widget` functionality to obtain the widget (currently there are no auto updates for widgets on plasma 6, and you can't update them via the update button, [relevant](https://bugs.kde.org/show_bug.cgi?id=483570) [issues](https://discuss.kde.org/t/kde-6-widgets-fail-to-update/14337))

If the applet doesn't get automatically added to your system tray, run:
```
systemctl --user restart plasma-plasmashell
```
This will restart your plasma shell or log out and back in.

#### Alternatively:
Use `kpackagetool6` (currently broken) or `plasmapkg2` (not part of a clean plasma 6 install)

```
git clone https://github.com/dhruv8sh/arch-update-checker/
cd arch-update-checker
kpackagetool6 -i .
```

**Comment by Kingproone** [comment]
@dhruv8sh just a ping if these are any good to update the readme, also, I installed 0.10 with plasmapkg2 since kptool6 seems to still be broken

**Comment by dhruv8sh** [comment]
These will require a few changes. I plan on publishing the next release in the .plasmoid format. This will provide another way to install. Also, now the applet itself asks to install the requirements if not installed already.

**Comment by Kingproone** [comment]
On that note, the finished items from the todo could be moved to a features section.
