### ISSUE TITLE
Pacman Update not Showing (CachyOS)

### ISSUE THREAD

**Issue by Syntist** [dhruv8sh/arch-update-checker#51]
Addon is pretty good, but am facing and issue, it doesn't show any updates while there is an update.

```❯ checkupdates
gettext 0.22.4-1.1 -> 0.22.5-1.1
glib2 2.80.2-1.1 -> 2.80.2-2.1
gtk3 1:3.24.41-1.1 -> 1:3.24.42-1.1
vulkan-icd-loader 1.3.279-1.1 -> 1.3.285-1.1
❯ 
❯ sud
zsh: command not found: sud
❯ 
❯ sudo pacman -Syu
:: Synchronizing package databases...
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
 core is up to date
 extra is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (4)                         Old Version    New Version    Net Change  Download Size

cachyos-core-v3/gettext             0.22.4-1.1     0.22.5-1.1       0.20 MiB       2.09 MiB
cachyos-core-v3/glib2               2.80.2-1.1     2.80.2-2.1       0.00 MiB       5.18 MiB
cachyos-extra-v3/gtk3               1:3.24.41-1.1  1:3.24.42-1.1    0.22 MiB       8.68 MiB
cachyos-extra-v3/vulkan-icd-loader  1.3.279-1.1    1.3.285-1.1      0.00 MiB       0.14 MiB

Total Download Size:   16.09 MiB
Total Installed Size:  99.41 MiB
Net Upgrade Size:       0.43 MiB

:: Proceed with installation? [Y/n] ^C
Interrupt signal received
```

![image](https://github.com/dhruv8sh/arch-update-checker/assets/24858150/114eb279-e010-4d78-8a82-fc44d614b3ae)
and when i refresh it shows no updates.

**Comment by dhruv8sh** [comment]
You need to have pacman-contrib and pacutils installed to fetch updates. Make sure you have those installed.

**Comment by Syntist** [comment]
OH thanks I was missing pacutils. 
It should be written in readme, that those package are needed, as it doesn't show any error.

**Comment by Syntist** [comment]
@dhruv8sh It was working, but after i update once, and when there are new updates. Now it get stucks
```❯ checkupdates
boost-libs 1.83.0-7.1 -> 1.83.0-8
icu 74.2-2.1 -> 75.1-1
kdeplasma-addons 6.0.4-1.1 -> 6.0.4-2
konsole 24.02.2-1.1 -> 24.02.2-2
libqalculate 5.1.1-1.1 -> 5.1.1-2
libwbclient 4.20.1-1.1 -> 4.20.1-2
libxml2 2.12.6-2.1 -> 2.12.7-1
plasma-desktop 6.0.4-1.1 -> 6.0.4-2
plasma-workspace 6.0.4-1.1 -> 6.0.4-2
qt5-base 5.15.13+kde+r145-1.1 -> 5.15.13+kde+r145-2
qt6-5compat 6.7.0-1.1 -> 6.7.0-2
qt6-base 6.7.0-6.1 -> 6.7.0-7
qt6-webengine 6.7.0-1.1 -> 6.7.0-2
raptor 2.0.16-4.1 -> 2.0.16-5
smbclient 4.20.1-1.1 -> 4.20.1-2
tracker3 3.7.3-1.1 -> 3.7.3-2
xfsprogs 6.7.0-1.1 -> 6.8.0-2
```


![image](https://github.com/dhruv8sh/arch-update-checker/assets/24858150/d4f1bb3c-1ff8-4931-aee1-e84a73f146d4)

**Comment by dhruv8sh** [comment]
Since your screenshot shows it's stuck on AUR Updates, can you check if you have the correct AUR Wrapper selected? If it is, check for updates using that wrapper. Like so, it is done with -Qua or -Qum for most.

**Comment by Syntist** [comment]
I tried the AUR it's working fine, as i am using Paru. but if you see the screenshot it shows it's stuck at Arch Repositories. Is there a way I can look into logs? or I can run it locally so, if i found the, issue I can upload the fix if needed.

**Comment by Syntist** [comment]
I pull the latest repo from here, and now it's working great. Good Plugin.

**Comment by dhruv8sh** [comment]
Perfect! Make sure to install the version I just released.
Star the project if you really love it.
