### ISSUE TITLE
Flatpak looking for update stuck

### ISSUE THREAD

**Issue by Syntist** [dhruv8sh/arch-update-checker#52]
Getting stuck on flatpak looking for update.
Version 
![image](https://github.com/dhruv8sh/arch-update-checker/assets/24858150/6eea3825-033e-48da-b536-8375e38333ed)

![image](https://github.com/dhruv8sh/arch-update-checker/assets/24858150/667db0bc-29d0-4aa3-ba09-9d8a529f9d7a)

**Comment by dhruv8sh** [comment]
Can you paste the output of ``` flatpak --remote-ls --updates ```?

**Comment by Syntist** [comment]
it happens, when i got gamescope updated and it kept reloading

**Comment by Syntist** [comment]
`
❯ flatpak remote-ls --updates
Name                            Application ID          Version       Branch       Arch
KDE Application Platform        org.kde.Platform                      6.7          x86_64
`
But it's keep looking for the update.
![image](https://github.com/dhruv8sh/arch-update-checker/assets/24858150/da7b89ea-0dc1-457e-bd22-c8f93f5dce7f)

**Comment by dhruv8sh** [comment]
Fixed in the latest commit. Will be shipped in the next release.
PS : It happened because of a caveat with how QML handles JS files.
