### ISSUE TITLE
Show MB or MiB instead of M (I don't know whether metric or binary is being used)

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#53]
Based on: https://en.wikipedia.org/wiki/Megabyte
also update K and possible G

![Screenshot_20240524_191035](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/28549aa5-928e-46e6-bb2c-acc7d184cd7b)

**Comment by dhruv8sh** [comment]
Fixed in the latest commit.
