### ISSUE TITLE
[Bug] After a full update, sometimes the widget stays in the updating mode

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#56]
![Screenshot_20240621_161910](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/540ecca3-2b1b-4d50-a602-16b2dcca7844)

Whilst like this, clicking the `Check for updates` does nothing, doing another update does not fix this either (howering the update all button in this state- maybe all the time does not show a popup description of the button like the update checker does).

**Comment by OlegAckbar** [comment]
Can confirm the issue.

**Comment by dhruv8sh** [comment]
There is a complete code cleanup coming up in a couple hours. It should solve these issues and make it easier to contribute and extend functionality.
It's also helping fix the finer details.

**Comment by dhruv8sh** [comment]
The new refactors are now up. It would be really helpful if you test them out and make sure they are release-worthy!
(In my opinion, I removed all of the little nitpicks. Even when you are watching info/updating/uninstalling a singular package the busy indicator is loaded in for that particular package only.)

**Comment by Kingproone** [comment]
So i did a full update and it crashed my shell, but this might have been because of a package that got updated. Will need to test again. Also, 6.1.2 should land any day now, that should tell wether updating plasma is the culprit.

**Comment by dhruv8sh** [comment]
I performed a full update. Did not crash for me, seems to be working.

**Comment by Kingproone** [comment]
Even though it crashed for some reason, whilst updating everything there was a busy indicator in the middle of the widget overlaying the list of my packages - looked just fine, and when I updated a single app the busy indicator was only showing up for that app, and after it finished updating it did a refresh when next opening the widget. (there was a moment it froze, but it might be because of a plasma bug, where updtaing an app locks up my taskbar)
