### ISSUE TITLE
[Bug] Regressions in 0.10

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#59]
1. missing fallback icon for the download button

![Screenshot_20240702_212626](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/0cc16ba0-49a4-416d-828c-b37d58877ea9)

2. no floating description for the resfresh and download buttons (the package ordering button has it)

3. when the widget is placed in the taskbar or on the desktop has no minimum size which allows for the following:

![Screenshot_20240702_213444](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/88a4c135-f491-4472-9787-c74fa8d08d35)
![Screenshot_20240702_213514](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/55b9bc7b-4e60-4043-9499-262587bef66a)

**Comment by dhruv8sh** [comment]
Good points about tooltip and minimum size. 
The first issue has to do with your icon theme. Nothing I can do about it. 

Just putting this here so I remember:
Fix notifications.
Add logging back
Remove "show intro" from config
Change pictures in the README

**Comment by Kingproone** [comment]
2.5. the pause button (moved to the buttom right) is also missing a floating message
4. when clicking the pause button it does not change the icon to a play button (was it like this before 0.10? i was not using that button)

**Comment by dhruv8sh** [comment]
The pause icon follows the HIG by KDE Plasma.

**Comment by Kingproone** [comment]
can I ask what point you're referring to? it's quite a few pages

**Comment by dhruv8sh** [comment]
I'll have to look through it, but it says something like - Only change icons for state-changing buttons(such as the sort button), if it is check-able don't bother changing because it's checked is indicative of the state.

**Comment by dhruv8sh** [comment]
Please pull and check the latest commits.

**Comment by Kingproone** [comment]
v 10.5
2. , 2.5 and 3. fixed. 4: I still feel should change between the play and the pause icon (kde' in house mpv video player: haruna does so as well)

the taskbar and desktop minimum size work, however the desktop version becomes a clickable button that opens the widget which looks quite funny
![Screenshot_20240707_113928](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/3989569b-65e1-41bc-8306-26f22569adab)

**Comment by Kingproone** [comment]
As a side note, if you press `shift + print screen` plasma will capture the current focused window so you dont have to go and crop them leaving in the 1 pixel wallpaper borders (currently the readme features these). Just turn off the option to capture window shadows.

**Comment by Kingproone** [comment]
I can also see that pamac support was deprecated. (I'm no manjaro fan, so I'll live) But since it is a regression I thought it was worth a mention.

**Comment by dhruv8sh** [comment]
> I still feel should change between the play and the pause icon

The checkable state of the button would make it confusing, I will go forward with the current method.

> the taskbar and desktop minimum size work, however the desktop version becomes a clickable button that opens the widget which looks quite funny

Fixed!

> pamac support was deprecated

Add info about this to the README
Changed the image with the visible wallpaper in the README

**Comment by Kingproone** [comment]
In the behaviour tab the option choose your preferred `terminal` is gone now, which wouldn't be that big of an issue, if it respected your system setting for default terminal app, which at the moment is not the case.

**Comment by Kingproone** [comment]
In the listview, next to the expand/collapse button the extensive information button has no hover message.
![Screenshot_20240719_001229](https://github.com/user-attachments/assets/a30eeeaa-c167-44c9-b640-6a0e70ba7fbb)
