### ISSUE TITLE
AUR Wrapper changes not being saved.

### ISSUE THREAD

**Issue by AirisLuna** [dhruv8sh/arch-update-checker#7]
When going to the update checker settings and changing the AUR Wrapper from paru to yay, the option to apply is greyed out, and if you change other settings and tries to save, the AUR Wrapper changes are not saved and it returns to paru.

![image](https://github.com/dhruv8sh/arch-update-checker/assets/13425006/cd127c84-325b-46e1-b734-f01220380398)

I'm not sure if it matters/relevant but I am using the fish shell.

**Comment by dhruv8sh** [comment]
I am surprised this went unnoticed up until now! The latest commit should work fine.
I'll also make a release out of this and publish it on the KDE Store.
Thanks for reporting.
